import Link from "next/link";
export function Badge({ status }: { status:string }) { const s=status.toUpperCase(); const color=s.includes("SUCCESS")||s==="ONLINE"?"var(--green)":s.includes("FAIL")||s.includes("REVOK")||s.includes("CANCEL")?"var(--red)":s.includes("RUN")||s.includes("BUILD")||s.includes("QUEUE")?"var(--yellow)":"var(--blue-soft)"; return <span style={{ display:"inline-flex",alignItems:"center",gap:6,color,background:`${color}18`,border:`1px solid ${color}40`,borderRadius:6,padding:"4px 10px",fontSize:11,fontWeight:700,whiteSpace:"nowrap" }}><span style={{ width:6,height:6,borderRadius:'50%',background:color }} />{s.replaceAll("_"," ")}</span>; }
export function Card({ children, style }: { children:React.ReactNode; style?:React.CSSProperties }) { return <section className="dp-card" style={{ padding:20, transition:"border-color .18s, transform .18s", ...style }}>{children}</section>; }
export function Stat({ label, value, detail, accent="var(--blue)" }: { label:string; value:string|number; detail?:string; accent?:string }) { return <Card style={{ position:"relative", overflow:"hidden", padding:"18px 20px 16px" }}><div style={{ display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:14 }}><div style={{ color:"var(--muted)",fontSize:12.5,fontWeight:600 }}>{label}</div><div style={{ width:32,height:32,borderRadius:8,background:`${accent}20`,color:accent,display:"grid",placeItems:"center",fontSize:16 }}>◈</div></div><div className="dp-mono" style={{ fontSize:28,fontWeight:600,letterSpacing:"-.01em" }}>{value}</div>{detail && <div style={{ color:"var(--faint)",fontSize:11,marginTop:9 }}>{detail}</div>}</Card>; }
export function SectionTitle({ title, href, action }: { title:string; href?:string; action?:string }) { return <div style={{ display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14,gap:12 }}><h2 style={{ fontSize:15,margin:0,letterSpacing:"-.01em" }}>{title}</h2>{href && <Link href={href} style={{ color:"var(--blue-soft)",fontSize:12.5,fontWeight:700,whiteSpace:"nowrap" }}>{action ?? "View all"} <span aria-hidden="true">→</span></Link>}</div>; }
export function Empty({ title, text, href, action }: { title:string;text:string;href?:string;action?:string }) { return <div style={{ textAlign:"center",padding:"52px 20px",border:"1px dashed var(--line-strong)",borderRadius:12,background:"#0d111855",color:"var(--muted)" }}><div style={{ width:42,height:42,display:"grid",placeItems:"center",margin:"0 auto 14px",borderRadius:"50%",background:"#5b7fff20",color:"var(--blue-soft)",fontSize:22 }}>◌</div><strong style={{ color:"var(--text)",display:"block",marginBottom:6 }}>{title}</strong><div style={{ fontSize:12,lineHeight:1.6 }}>{text}</div>{href && <Link className="dp-btn dp-btn-primary" href={href} style={{ display:"inline-block",marginTop:18,fontSize:12 }}>{action ?? "Get started"}</Link>}</div>; }
export function formatDate(value?:string|null) { return value ? new Date(value).toLocaleString([], { month:"short",day:"numeric",hour:"2-digit",minute:"2-digit" }) : "—"; }

export function PageHeader({ eyebrow, title, description, action }: { eyebrow:string; title:string; description?:string; action?:React.ReactNode }) { return <header style={{ display:"flex", justifyContent:"space-between", gap:20, alignItems:"flex-start", marginBottom:28, flexWrap:"wrap" }}><div><div className="dp-kicker" style={{ marginBottom:10 }}>{eyebrow}</div><h1 style={{ margin:0, fontSize:"clamp(25px,3vw,34px)", letterSpacing:"-.055em" }}>{title}</h1>{description && <p style={{ margin:"9px 0 0", color:"var(--muted)", maxWidth:680, lineHeight:1.6 }}>{description}</p>}</div>{action}</header>; }
